version: '3.8'

services:
    web:
        build: .
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/transactions_db
            - REDIS_URL=redis://localhost:6379/0
            - API_KEY = secret_api_key
        depends_on:
            - db
            - redis

    celery_worker:
        build: .
        command: celery -A app.tasks worker --loglevel=info
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/transactions_db
            - REDIS_URL=redis://localhost:6379/0
        depends_on:
            - redis
            - db

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: transactions_db
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:6

volumes:
    postgres_data: