name: Python Continuous Integration

on:
    pull_request:
        branches:
            - main

jobs:
    test_pull_rquest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - run: pip install -r requirements.txt
            - run: pytest app/tests/tests_api.py


